FROM debian:{{.VersionCodename}}
{{if .Archived}}
COPY sources.list /etc/apt/sources.list
{{end}}
WORKDIR /workspace
COPY docker-entrypoint.sh .
RUN chmod a+x docker-entrypoint.sh
VOLUME /workspace/packages
ENTRYPOINT ["./docker-entrypoint.sh"]
